// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.NullUUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Name      string
}
